### ISSUE TITLE
Matching Line number with Disassembled code

### ISSUE THREAD

**Issue by popthink** [plume-oss/plume#133]
Currently Line number of AST node is holding line of source code.

I think that plume should make them more friendly with disassembled bytecode.

I mean that changing linenumber of source to offset of bytecode from method entry.

**Comment by DavidBakerEffendi** [comment]
This is quite a complicated task depending on the information you have. e.g. when compiling source code with debugging information, the line number information corresponds directly with the source code otherwise it does not. 

Android bytecode, for example, does contain column number information whereas normal JVM bytecode does not. There are many threads on the internet that try these tasks but there are many counter-examples which could cause issues with various techniques.
